### ISSUE TITLE
Remove t/lib/Test from the repo?

### ISSUE THREAD

**Issue by toddr** [Perl-Toolchain-Gang/ExtUtils-Install#24]
I just noticed that t/lib includes what looks like files from Test::Simple. The changes seem to pre-date git so I can't determine the reason but I would guess that it is no longer relevant. Can anyone comment if that's the case?

**Comment by toddr** [comment]
I've submitted a PR just to see if it breaks any CI.

**Comment by toddr** [comment]
More research reveals that it was added in 1.3701 2006-03-13 20:00. Probably by @demerphq 

https://metacpan.org/changes/distribution/ExtUtils-Install#L384

The addition was to support 5.005 but at this point we have our statements in the code here, so there's no way 5.005 is supported at this point. I think it would be a safe removal.

**Comment by haarg** [comment]
5.005 isn't an issue, but this would matter on 5.6.1. Updating the toolchain on 5.6.1 is already pretty broken though, and generally requires skipping tests.

**Comment by mohawk2** [comment]
I thought we only supported 5.6.2, and that only on a "patches accepted" basis? Do we support 5.6.1 at all? (if that's relevant to this specific point)

**Comment by haarg** [comment]
Just wanted to clarify that it wasn't only an issue with 5.005. I think it's a reasonable change.
